name: Deploy to gh-pages

on:
  push:
    branches:
      - main

jobs:
  publish-gh-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3.0.0
        with:
          persist-credentials: false

      - name: Install and Build 🔧
        run: |
          npm ci --production --audit=false
          npm run build -- --base=/game-dialogue/

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          BRANCH: gh-pages
          FOLDER: dist
          CLEAN: true
          clean-exclude: |
            .nojekyll
